<start>             ::= <rule> <rule_end> | <first_rule> <start>
<first_rule>        ::= <rule> <rule_end>
<rule>              ::= <atom> <entailments> | <implications> <atom> | <implies> <atom> | <id> <opt_args> | /^[a-zA-Z]+[a-zA-Z0-9_]*$/
<entailments>       ::= <entails> <atom_list>
<implications>      ::= <atom_list> <implies>
<atom_list>         ::= <atom> <atom_list_rest> | <id> <opt_args> | /^[a-zA-Z]+[a-zA-Z0-9_]*$/
<atom_list_rest>    ::= <separator> <atom_list>
<atom>              ::= <id> <opt_args> | /^[a-zA-Z]+[a-zA-Z0-9_]*$/
<opt_args>          ::= <open_paranthesis> <close_paranthesis> | <open_paranthesis> <args>
<args>              ::= <atom_list> <close_paranthesis>
<open_paranthesis>  ::= '('
<close_paranthesis> ::= ')'
<id>                ::= /^[a-zA-Z]+[a-zA-Z0-9_]*$/
<separator>         ::= ','
<entails>           ::= ':-'
<implies>           ::= '->'
<rule_end>          ::= '.\n'

